#!/bin/sh

set -e    # halt on first error

./buildgc
./buildcii
./buildstate
./buildastronode
./buildwalk

FLAGS="-O3 -Wall"
CC=gcc
INCLUDES="-I./state -I./astronode -I./walk -I./astrogc/gc/include -I./astrogc"

LINKS="$PWD/libgc.dll.a $PWD/cii/array.o $PWD/cii/assert.o $PWD/state/symtab.o " 
LINKS+="$PWD/cii/except.o $PWD/cii/mem.o $PWD/cii/seq.o $PWD/cii/table.o "
LINKS+="$PWD/state/state.o $PWD/walk/walk.o $PWD/astronode/astronode.o "
LINKS+="$PWD/astrogc/astrogc.o libgc.dll.a"

CC $FLAGS $INCLUDES "-I$PWD/cii" test.c -o test $LINKS