name: Testing Github Actions
on: [push]
jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running tests:"
            - run: python ${{ github.workspace }}/asteroid/test-suites/run-tests.py
