name: Testing Github Actions
on: [push]
jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running tests:"
            - name: List files in repository
              run: |
                  ls ${{ github.workspace }}
