name: Main Job
on: [push]
env:
    PYTHONPATH: ${{ github.workspace }}
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Run tests
        run: |
            pip install -r requirements.txt
            python asteroid/test-suites/run-tests.py

      - name: Generate documentation
        run: |
            bash docs/run_docs
