name: Main Job
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: List asteroid dir
        run: |
          echo ${{ github.workspace }}/asteroid/ >> $GITHUB_PATH
          python ${{ github.workspace }}/asteroid/test-suites/run-tests.py

