name: Main Job
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: List asteroid dir
        run: |
          ls ${{ github.workspace }}/asteroid/

