name: Main Job
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Run tests
        run: |
          pip install -e .
          python ${{ github.workspace }}/asteroid/test-suites/run-tests.py

